import { OutpostState, OutpostLocation, OutpostModule, Astronaut, MissionObjective } from './simulation-types';

export function getInitialScenario(location: OutpostLocation): OutpostState {
  const isMoon = location === 'moon';

  const modules: OutpostModule[] = [
    {
      id: 'mod-core-hab',
      name: 'Primary Habitation Module',
      category: 'habitat',
      level: 1,
      maxLevel: 3,
      powerConsumption: 2.0,
      waterConsumption: 0,
      isActive: true,
      health: 100,
      description: 'Pressurized living quarters, galley, and medical monitoring suite for the crew.',
      techFact: 'NASA TransHab concepts use multi-layer Kevlar and Nextel fabric walls that inflate in space.',
      buildCost: { regolith: 0, power: 0 },
      gridPosition: { x: 3, y: 3 },
    },
    {
      id: 'mod-solar-array-1',
      name: 'Ultraflex Solar PV Array Alpha',
      category: 'power',
      level: 1,
      maxLevel: 4,
      powerConsumption: -12.0, // generates up to 12 kW
      waterConsumption: 0,
      isActive: true,
      health: 100,
      description: 'Tracking gallium-arsenide solar wings capturing solar irradiance.',
      techFact: 'The ISS solar arrays produce up to 120 kW in direct sunlight using double-sided silicon cells.',
      buildCost: { regolith: 5, power: 3 },
      gridPosition: { x: 1, y: 2 },
    },
    {
      id: 'mod-battery-bank',
      name: 'Solid-State Battery Storage',
      category: 'power',
      level: 1,
      maxLevel: 3,
      powerConsumption: 0.5,
      waterConsumption: 0,
      isActive: true,
      health: 100,
      description: 'High-density energy storage providing power during nocturnal phases and dust storms.',
      techFact: 'NASA Artemis uses lithium-iron-phosphate and solid-state cells engineered for -150°C thermal stability.',
      buildCost: { regolith: 8, power: 4 },
      gridPosition: { x: 2, y: 2 },
    },
    {
      id: 'mod-kilopower',
      name: 'Kilopower Fission Reactor',
      category: 'power',
      level: isMoon ? 1 : 0, // Moon starts with nuclear for the 14-day night!
      maxLevel: 3,
      powerConsumption: isMoon ? -10.0 : 0,
      waterConsumption: 0,
      isActive: isMoon,
      health: 100,
      description: 'Compact uranium fission reactor with Stirling power conversion, immune to darkness.',
      techFact: 'NASA KRUSTY (Kilopower) reactor tested at Nevada National Security Site proves 1-10 kWe scalable fission.',
      buildCost: { regolith: 25, power: 15 },
      gridPosition: { x: 5, y: 1 },
    },
    {
      id: 'mod-sabatier',
      name: 'Sabatier O₂ / H₂O Processor',
      category: 'life-support',
      level: 1,
      maxLevel: 3,
      powerConsumption: 3.5,
      waterConsumption: 0,
      isActive: true,
      health: 100,
      description: 'Catalytic reactor reacting carbon dioxide and hydrogen at 400°C to yield water and oxygen.',
      techFact: 'The Sabatier system on the ISS recovers over 50% of oxygen from exhaled crew carbon dioxide.',
      buildCost: { regolith: 10, power: 6 },
      gridPosition: { x: 2, y: 4 },
    },
    {
      id: 'mod-cdra',
      name: 'Amine Thermal CO₂ Scrubber',
      category: 'life-support',
      level: 1,
      maxLevel: 3,
      powerConsumption: 2.2,
      waterConsumption: 0,
      isActive: true,
      health: 100,
      description: 'Solid amine adsorption beds removing toxic metabolic CO2 from the outpost atmosphere.',
      techFact: 'High CO2 (>2,500 ppm) causes astronaut headaches, cognitive impairment, and lethargy.',
      buildCost: { regolith: 6, power: 4 },
      gridPosition: { x: 4, y: 4 },
    },
    {
      id: 'mod-water-recovery',
      name: 'Vapor Compression Water Distiller',
      category: 'life-support',
      level: 1,
      maxLevel: 3,
      powerConsumption: 2.8,
      waterConsumption: 0,
      isActive: true,
      health: 100,
      description: 'Purifies greywater, atmospheric condensate, and crew urine into pristine drinking water.',
      techFact: 'NASA astronaut Don Pettit famously noted: "Yesterday’s coffee becomes today’s coffee."',
      buildCost: { regolith: 8, power: 5 },
      gridPosition: { x: 3, y: 4 },
    },
    {
      id: 'mod-greenhouse',
      name: 'Bio-Regenerative Hydroponic Dome',
      category: 'agriculture',
      level: 1,
      maxLevel: 3,
      powerConsumption: 3.8, // grow lights require continuous power
      waterConsumption: 4.0,
      isActive: true,
      health: 100,
      description: 'Multi-tier aeroponic racks growing dwarf potatoes, salad greens, and micro-radishes.',
      techFact: 'NASA Vegetable Production System (Veggie) on ISS has grown red romaine lettuce and zinnia flowers.',
      buildCost: { regolith: 15, power: 8 },
      gridPosition: { x: 4, y: 2 },
    },
    {
      id: 'mod-regolith-sinterer',
      name: 'ISRU 3D Regolith Sintering Bot',
      category: 'shielding',
      level: 1,
      maxLevel: 4,
      powerConsumption: 3.0,
      waterConsumption: 0,
      isActive: true,
      health: 100,
      description: 'Autonomous microwave sintering printer building interlocking lunar/martian rock shields.',
      techFact: 'Sintered regolith absorbs both cosmic ionizing radiation and protects against hypervelocity micrometeoroids.',
      buildCost: { regolith: 12, power: 5 },
      gridPosition: { x: 5, y: 3 },
    },
    {
      id: 'mod-storm-shelter',
      name: 'Core Storm Shelter & Water Vault',
      category: 'habitat',
      level: 1,
      maxLevel: 2,
      powerConsumption: 1.0,
      waterConsumption: 0,
      isActive: true,
      health: 100,
      description: 'Deep subterranean bunker insulated by surrounding water supply bladders.',
      techFact: 'Water molecules contain hydrogen atoms, which are superior absorbers of solar flare protons.',
      buildCost: { regolith: 20, power: 10 },
      gridPosition: { x: 3, y: 2 },
    },
  ];

  const crew: Astronaut[] = [
    {
      id: 'crew-1',
      name: 'Commander Elena Vance',
      role: 'Commander',
      avatar: '👨‍🚀',
      health: 100,
      morale: 95,
      fatigue: 15,
      radiationDose: 4.2,
      status: 'active',
      specialtySkill: 'Mission command: boosts overall outpost sustainability score and prevents morale panic.',
    },
    {
      id: 'crew-2',
      name: 'Marcus Cole',
      role: 'Systems Engineer',
      avatar: '👩‍🚀',
      health: 100,
      morale: 90,
      fatigue: 20,
      radiationDose: 5.1,
      status: 'active',
      specialtySkill: 'Rapid EVA repair and optimization of power grid and battery life.',
    },
    {
      id: 'crew-3',
      name: 'Dr. Maya Lin',
      role: 'Astrobiologist',
      avatar: '🧑‍🚀',
      health: 100,
      morale: 92,
      fatigue: 18,
      radiationDose: 3.8,
      status: 'active',
      specialtySkill: 'Hydroponics master: increases crop growth rate and oxygen output by 25%.',
    },
    {
      id: 'crew-4',
      name: 'Dr. Tariq Al-Mansoor',
      role: 'Flight Surgeon',
      avatar: '👨‍⚕️',
      health: 100,
      morale: 88,
      fatigue: 22,
      radiationDose: 4.0,
      status: 'active',
      specialtySkill: 'Bio-telemetry monitor: rapidly detects radiation sickness and treats fatigue.',
    },
  ];

  const objectives: MissionObjective[] = [
    {
      id: 'obj-survive-30',
      title: 'Sol 30 Milestone',
      description: 'Establish outpost equilibrium and survive the first 30 Sols without catastrophic failure.',
      targetValue: 30,
      currentValue: 1,
      unit: 'Sols',
      completed: false,
      nasaContext: 'NASA analog simulations (like CHAPEA and HERA) test long-duration mission protocols.',
    },
    {
      id: 'obj-sinter-shield',
      title: 'Construct 40cm Regolith Shield',
      description: 'Mine and sinter 40 cm of planetary regolith over habitat modules to deflect radiation.',
      targetValue: 40,
      currentValue: 15,
      unit: 'cm',
      completed: false,
      nasaContext: '40-50 cm of sintered regolith eliminates ~85% of cosmic ray background dose.',
    },
    {
      id: 'obj-first-harvest',
      title: 'Bio-Regenerative Harvest',
      description: 'Complete at least one full harvest cycle in the hydroponic greenhouse.',
      targetValue: 100,
      currentValue: 0,
      unit: '%',
      completed: false,
      nasaContext: 'Self-sustaining nutrition eliminates the enormous mass penalty of Earth resupply rockets.',
    },
    {
      id: 'obj-clean-air',
      title: 'Atmospheric Stewardship',
      description: 'Keep internal carbon dioxide below 1200 ppm and oxygen pressure above 19.5 kPa.',
      targetValue: 1200,
      currentValue: 650,
      unit: 'ppm',
      completed: false,
      nasaContext: 'NASA astronauts experience reduced cognitive function when CO2 exceeds 2000 ppm.',
    },
  ];

  return {
    missionId: `mission-${location}-${Date.now()}`,
    location,
    outpostName: isMoon ? 'Artemis Base Alpha (Shackleton Crater)' : 'Ares Outpost Prime (Jezero Crater)',
    currentSol: 1,
    solProgress: 0.15,
    isDaytime: true,
    speed: 1,
    isPaused: false,
    gameOver: false,
    gameWon: false,
    resources: {
      powerGeneration: isMoon ? 18.0 : 15.0,
      powerDemand: 14.5,
      batteryStored: isMoon ? 85.0 : 60.0,
      batteryCapacity: 100.0,
      o2Reserve: 150.0,
      o2Capacity: 200.0,
      o2PartialPressure: 21.0,
      co2Level: 620,
      waterReserve: 450.0,
      waterCapacity: 600.0,
      waterRecyclingEfficiency: 95,
      cabinPressure: 101.3,
      internalTemp: 21.5,
      ambientRadiation: isMoon ? 0.06 : 0.03,
      internalRadiation: 0.02,
      cumulativeRadiation: 4.5,
      shieldingThicknessCm: 15,
      stormShelterActive: false,
      foodRations: 120, // ~10 days initial supply
      cropHarvestProgress: 15,
      cropHealth: 100,
      dailyCalorieOutput: 2400,
      regolithStored: 18,
      isruProductionRate: 3.5,
    },
    modules,
    crew,
    activeHazards: [],
    logs: [
      {
        id: 'log-init',
        sol: 1,
        timeString: 'SOL 001 - 06:00',
        message: `MISSION INITIALIZED: ${isMoon ? 'Artemis Base Alpha' : 'Ares Outpost Prime'} systems online. All telemetry nominal.`,
        type: 'info',
      },
    ],
    objectives,
    sustainabilityScore: 88,
    sciencePoints: 50,
  };
}
